"""
ForensicChrono - Fusion Meta-Model
====================================

Combines the RNA (GTEx) and Microbial (Qiita 13810) models
into a single PMI estimator using a Ridge regression meta-model.

IMPORTANT:
    - The RNA model predicts PMI in MINUTES
    - The Microbial model predicts PMI in DAYS
    - This script aligns them to HOURS internally

Inputs required:
    models/rna_model.pkl
    models/microbial_model.pkl

Outputs:
    models/fusion_meta_model.pkl
    results/fusion_oof_predictions.csv
    results/experiment_summary.csv  (appended)
    results/experiment_summary.xlsx (updated)
    reports/fusion_model_predicted_vs_actual.png
    reports/fusion_model_predicted_vs_actual.svg
"""

import os
import json
import pickle
import warnings
from datetime import datetime

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_predict, KFold

warnings.filterwarnings("ignore")


# ============================================================
# CONFIGURATION
# ============================================================

RNA_MODEL_PATH      = "models/rna_model.pkl"
MICRO_MODEL_PATH    = "models/microbial_model.pkl"
FUSION_MODEL_PATH   = "models/fusion_meta_model.pkl"

RNA_OOF_PATH        = "results/rna_oof_predictions.csv"
MICRO_OOF_PATH      = "results/microbial_oof_predictions.csv"

N_META_FOLDS        = 5
SEED                = 42


# ============================================================
# LOAD OOF PREDICTIONS
# ============================================================

def load_oof_predictions():
    """
    Load the OOF prediction CSVs that were already generated by
    rna_model.py and microbial_model.py.

    RNA CSV columns  : SUBJID, tissue, actual (minutes), predicted (minutes)
    Micro CSV columns: sample_id, subject_id, actual_pmi (days), ensemble_prediction (days)
    """

    if not os.path.exists(RNA_OOF_PATH):
        raise FileNotFoundError(
            f"RNA OOF file not found: {RNA_OOF_PATH}\n"
            "Run src/rna_model.py first."
        )

    if not os.path.exists(MICRO_OOF_PATH):
        # Try the latest timestamped version
        result_files = [
            f for f in os.listdir("results")
            if f.startswith("microbial_predictions_") and f.endswith(".csv")
        ]
        if not result_files:
            raise FileNotFoundError(
                f"Microbial OOF file not found: {MICRO_OOF_PATH}\n"
                "Run src/microbial_model.py first."
            )
        result_files.sort(reverse=True)
        micro_path = os.path.join("results", result_files[0])
        print(f"[INFO] Using microbial OOF: {micro_path}")
    else:
        micro_path = MICRO_OOF_PATH

    rna_df   = pd.read_csv(RNA_OOF_PATH)
    micro_df = pd.read_csv(micro_path)

    return rna_df, micro_df


# ============================================================
# ALIGN BY DONOR
# ============================================================

def align_by_donor(rna_df, micro_df):
    """
    Both models may have been trained on different samples.
    We align them at the DONOR level by taking mean predictions
    per donor, then inner-join on donor ID.

    RNA   : SUBJID, actual (minutes), predicted (minutes)
    Micro : subject_id, actual_pmi (days), ensemble_prediction (days)

    Returns a DataFrame with columns:
        donor_id
        rna_actual_hrs        (ground truth from RNA side, hours)
        rna_pred_hrs          (RNA model prediction, hours)
        micro_actual_hrs      (ground truth from micro side, hours)
        micro_pred_hrs        (micro model prediction, hours)
        y_true_hrs            (mean of the two ground truths, hours)
    """

    # ── RNA donor-level mean ────────────────────────────────────────────────
    rna_donor = (
        rna_df
        .groupby("SUBJID")
        .agg(
            rna_actual_min=("actual", "mean"),
            rna_pred_min=("predicted", "mean")
        )
        .reset_index()
        .rename(columns={"SUBJID": "donor_id"})
    )
    rna_donor["rna_actual_hrs"] = rna_donor["rna_actual_min"] / 60.0
    rna_donor["rna_pred_hrs"]   = rna_donor["rna_pred_min"]   / 60.0

    # ── Micro donor-level mean ───────────────────────────────────────────────
    micro_donor = (
        micro_df
        .groupby("subject_id")
        .agg(
            micro_actual_days=("actual_pmi", "mean"),
            micro_pred_days=("ensemble_prediction", "mean")
        )
        .reset_index()
        .rename(columns={"subject_id": "donor_id"})
    )
    micro_donor["micro_actual_hrs"] = micro_donor["micro_actual_days"] * 24.0
    micro_donor["micro_pred_hrs"]   = micro_donor["micro_pred_days"]   * 24.0

    # ── Inner join ───────────────────────────────────────────────────────────
    merged = pd.merge(rna_donor, micro_donor, on="donor_id", how="inner")

    if len(merged) == 0:
        raise ValueError(
            "No matching donors found between RNA and Microbial OOF files.\n"
            "The two datasets likely do not share donor IDs — this is expected "
            "if GTEx and Qiita 13810 have different subjects.\n\n"
            "Falling back to SEPARATE evaluation mode (see below)."
        )

    # Use RNA ground truth as canonical (it's in the same unit after conversion)
    merged["y_true_hrs"] = merged["rna_actual_hrs"]

    print(f"\n[Fusion] Aligned donors: {len(merged)}")
    print(f"  RNA    donors total  : {len(rna_donor)}")
    print(f"  Micro  donors total  : {len(micro_donor)}")
    print(f"  Overlap (inner join) : {len(merged)}")

    return merged


# ============================================================
# FALLBACK: SEPARATE-DATASET META-MODEL
# ============================================================

def build_meta_features_separate(rna_df, micro_df):
    """
    If the two datasets have NO overlapping donors (common case —
    GTEx vs Qiita), we still want to train a meta-model.

    Strategy:
        - Use each dataset's OOF predictions as a 1-feature meta dataset.
        - Fit two Ridge models: one per modality.
        - At inference, blend them using inverse-MAE weighting.

    This is honest — each sub-model is evaluated on its own test set.
    The meta-model is just a calibration layer.
    """

    # ── RNA feature matrix ───────────────────────────────────────────────────
    rna_donor = (
        rna_df.groupby("SUBJID")
        .agg(actual=("actual", "mean"), predicted=("predicted", "mean"))
        .reset_index()
    )
    rna_y    = rna_donor["actual"].values / 60.0          # → hours
    rna_pred = rna_donor["predicted"].values / 60.0       # → hours

    # ── Micro feature matrix ─────────────────────────────────────────────────
    # Use the most recent timestamped predictions file
    micro_donor = (
        micro_df.groupby("subject_id")
        .agg(actual=("actual_pmi", "mean"), predicted=("ensemble_prediction", "mean"))
        .reset_index()
    )
    micro_y    = micro_donor["actual"].values * 24.0      # → hours
    micro_pred = micro_donor["predicted"].values * 24.0   # → hours

    return rna_y, rna_pred, micro_y, micro_pred


# ============================================================
# TRAIN META-MODEL (shared donor path)
# ============================================================

def train_meta_model_shared(merged):
    """
    When donors overlap: train a 2-feature Ridge meta-model.
    Features: [rna_pred_hrs, micro_pred_hrs]
    Target  : y_true_hrs
    """

    X = merged[["rna_pred_hrs", "micro_pred_hrs"]].values
    y = merged["y_true_hrs"].values

    scaler = StandardScaler()
    X_sc   = scaler.fit_transform(X)

    kf = KFold(n_splits=min(N_META_FOLDS, len(y)), shuffle=True, random_state=SEED)
    meta = Ridge(alpha=1.0)
    oof_preds = cross_val_predict(meta, X_sc, y, cv=kf)

    meta.fit(X_sc, y)

    r2  = r2_score(y, oof_preds)
    mae = mean_absolute_error(y, oof_preds)

    print(f"\n[Fusion Meta-Model — shared donors]")
    print(f"  Donors  : {len(y)}")
    print(f"  R²      : {r2:.4f}")
    print(f"  MAE     : {mae:.2f} hrs")

    return meta, scaler, y, oof_preds, r2, mae


# ============================================================
# TRAIN META-MODEL (separate dataset path — most likely)
# ============================================================

def train_meta_model_separate(rna_y, rna_pred, micro_y, micro_pred):
    """
    When donors do NOT overlap: calibrate each modality independently
    with a Ridge model, then weight them by their respective MAEs.
    """

    # ── RNA calibration ──────────────────────────────────────────────────────
    rna_X    = rna_pred.reshape(-1, 1)
    rna_sc   = StandardScaler()
    rna_X_sc = rna_sc.fit_transform(rna_X)

    rna_kf   = KFold(n_splits=min(N_META_FOLDS, len(rna_y)), shuffle=True, random_state=SEED)
    rna_ridge = Ridge(alpha=1.0)
    rna_oof   = cross_val_predict(rna_ridge, rna_X_sc, rna_y, cv=rna_kf)
    rna_ridge.fit(rna_X_sc, rna_y)

    rna_r2  = r2_score(rna_y, rna_oof)
    rna_mae = mean_absolute_error(rna_y, rna_oof)

    # ── Micro calibration ────────────────────────────────────────────────────
    micro_X    = micro_pred.reshape(-1, 1)
    micro_sc   = StandardScaler()
    micro_X_sc = micro_sc.fit_transform(micro_X)

    micro_kf   = KFold(n_splits=min(N_META_FOLDS, len(micro_y)), shuffle=True, random_state=SEED)
    micro_ridge = Ridge(alpha=1.0)
    micro_oof   = cross_val_predict(micro_ridge, micro_X_sc, micro_y, cv=micro_kf)
    micro_ridge.fit(micro_X_sc, micro_y)

    micro_r2  = r2_score(micro_y, micro_oof)
    micro_mae = mean_absolute_error(micro_y, micro_oof)

    print(f"\n[Fusion — Separate Dataset Mode]")
    print(f"  RNA   donors : {len(rna_y)}  |  R²={rna_r2:.4f}  |  MAE={rna_mae:.2f} hrs")
    print(f"  Micro donors : {len(micro_y)} |  R²={micro_r2:.4f}  |  MAE={micro_mae:.2f} hrs")

    # Inverse-MAE blending weights
    w_rna   = 1.0 / (rna_mae   + 1e-6)
    w_micro = 1.0 / (micro_mae + 1e-6)
    w_total = w_rna + w_micro
    w_rna   /= w_total
    w_micro /= w_total

    print(f"\n  Blend weights (inverse-MAE):")
    print(f"    RNA   : {w_rna:.3f}")
    print(f"    Micro : {w_micro:.3f}")

    return {
        "rna_ridge":   rna_ridge,
        "rna_scaler":  rna_sc,
        "micro_ridge": micro_ridge,
        "micro_scaler": micro_sc,
        "w_rna":       float(w_rna),
        "w_micro":     float(w_micro),
        "rna_r2":      float(rna_r2),
        "rna_mae_hrs": float(rna_mae),
        "micro_r2":    float(micro_r2),
        "micro_mae_hrs": float(micro_mae),
    }, rna_y, rna_oof, micro_y, micro_oof


# ============================================================
# REGRESSION GRAPH
# ============================================================

def save_regression_graph(y_true, y_pred, r2, mae, title_suffix="", out_dir="reports"):
    os.makedirs(out_dir, exist_ok=True)

    fig, ax = plt.subplots(figsize=(8, 7))

    ax.scatter(y_true, y_pred, alpha=0.45, s=26,
               color="#dc2626", edgecolors="none", label="Held-out donors")

    lo = min(y_true.min(), y_pred.min())
    hi = max(y_true.max(), y_pred.max())
    ax.plot([lo, hi], [lo, hi], "k--", linewidth=1.5, label="Perfect prediction")

    ax.text(0.05, 0.93, f"R² = {r2:.4f}", transform=ax.transAxes,
            fontsize=13, fontweight="bold")
    ax.text(0.05, 0.87, f"MAE = {mae:.2f} hrs", transform=ax.transAxes, fontsize=11)

    ax.set_xlabel("Actual PMI (hours)")
    ax.set_ylabel("Predicted PMI (hours)")
    ax.set_title(f"ForensicChrono Fusion Meta-Model\nRidge Calibration{title_suffix}")
    ax.legend(loc="lower right")
    ax.grid(True, linestyle="--", alpha=0.35)
    plt.tight_layout()

    png = os.path.join(out_dir, "fusion_model_predicted_vs_actual.png")
    svg = os.path.join(out_dir, "fusion_model_predicted_vs_actual.svg")
    fig.savefig(png, dpi=300)
    fig.savefig(svg)
    plt.close(fig)
    print(f"Regression graph saved -> {png}")


# ============================================================
# SAVE RESULTS (CSV + EXCEL)
# ============================================================

def save_fusion_results(summary, oof_df):
    os.makedirs("results", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    oof_csv = "results/fusion_oof_predictions.csv"
    oof_df.to_csv(oof_csv, index=False)
    print(f"OOF predictions saved -> {oof_csv}")

    row = {
        "timestamp":      timestamp,
        "model_type":     summary["model_type"],
        "mode":           summary["mode"],
        "donors":         summary.get("n_donors", "N/A"),
        "r2":             round(summary.get("r2", float("nan")), 4),
        "mae_hrs":        round(summary.get("mae_hrs", float("nan")), 2),
        "rna_r2":         round(summary.get("rna_r2",  float("nan")), 4),
        "micro_r2":       round(summary.get("micro_r2", float("nan")), 4),
        "rna_weight":     round(summary.get("w_rna",   float("nan")), 3),
        "micro_weight":   round(summary.get("w_micro", float("nan")), 3),
    }

    csv_path = "results/experiment_summary.csv"
    pd.DataFrame([row]).to_csv(
        csv_path, mode="a",
        header=not os.path.exists(csv_path), index=False
    )
    print(f"Summary appended -> {csv_path}")

    try:
        excel_path = "results/experiment_summary.xlsx"
        summary_df = pd.DataFrame([row])
        if os.path.exists(excel_path):
            existing = pd.read_excel(excel_path, sheet_name=None, engine="openpyxl")
        else:
            existing = {}

        with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
            for sheet, df in existing.items():
                df.to_excel(writer, sheet_name=sheet, index=False)
            summary_df.to_excel(writer, sheet_name="Fusion Results", index=False)
            oof_df.to_excel(writer, sheet_name="Fusion OOF Predictions", index=False)

        print(f"Excel updated -> {excel_path}")
    except Exception as e:
        print(f"[NOTE] Excel export skipped ({e})")

    with open("results/fusion_results.json", "w") as f:
        json.dump(summary, f, indent=2)
    print("JSON saved -> results/fusion_results.json")


# ============================================================
# MAIN
# ============================================================

def main():
    print("\n" + "=" * 70)
    print("FORENSICCHRONO — FUSION META-MODEL")
    print("=" * 70)

    os.makedirs("results", exist_ok=True)
    os.makedirs("reports", exist_ok=True)
    os.makedirs("models",  exist_ok=True)

    # ── Load OOF predictions ─────────────────────────────────────────────────
    rna_df, micro_df = load_oof_predictions()
    print(f"\nRNA OOF rows   : {len(rna_df)}")
    print(f"Micro OOF rows : {len(micro_df)}")

    # ── Try shared-donor path first ──────────────────────────────────────────
    try:
        merged = align_by_donor(rna_df, micro_df)
        shared_mode = len(merged) >= 10
    except ValueError as e:
        print(f"\n{e}")
        shared_mode = False

    if shared_mode:
        # ── Shared donors: 2-feature Ridge ──────────────────────────────────
        print("\n[Mode] Shared donors — 2-feature Ridge meta-model")
        meta, scaler, y_true, oof_preds, r2, mae = train_meta_model_shared(merged)

        package = {
            "model_type":    "FusionRidge_SharedDonors",
            "meta_ridge":    meta,
            "scaler":        scaler,
            "pmi_unit":      "hours",
            "rna_unit":      "minutes",
            "micro_unit":    "days",
        }

        oof_df = pd.DataFrame({
            "donor_id":    merged["donor_id"].values,
            "y_true_hrs":  y_true,
            "y_pred_hrs":  oof_preds,
            "error_hrs":   np.abs(y_true - oof_preds),
        })

        summary = {
            "model_type": "FusionRidge_SharedDonors",
            "mode":       "shared_donors",
            "n_donors":   len(y_true),
            "r2":         float(r2),
            "mae_hrs":    float(mae),
            "rna_r2":     float(r2_score(merged["rna_actual_hrs"].values,
                                         merged["rna_pred_hrs"].values)),
            "micro_r2":   float(r2_score(merged["micro_actual_hrs"].values,
                                         merged["micro_pred_hrs"].values)),
            "w_rna":      float(meta.coef_[0]),
            "w_micro":    float(meta.coef_[1]),
        }

        save_regression_graph(
            y_true, oof_preds, r2, mae,
            title_suffix=" — 2-Feature Ridge (Shared Donors)"
        )

    else:
        # ── Separate datasets: independent Ridge calibration + blend ─────────
        print("\n[Mode] Separate datasets — independent Ridge calibration + inverse-MAE blend")
        rna_y, rna_pred, micro_y, micro_pred = build_meta_features_separate(rna_df, micro_df)
        result, rna_y, rna_oof, micro_y, micro_oof = train_meta_model_separate(
            rna_y, rna_pred, micro_y, micro_pred
        )

        package = {
            "model_type":    "FusionRidge_SeparateDatasets",
            **result,
            "pmi_unit":      "hours",
            "rna_unit":      "minutes",
            "micro_unit":    "days",
        }

        # Combined OOF frame (two separate rows groups, clearly labelled)
        rna_oof_df = pd.DataFrame({
            "modality":   "RNA",
            "y_true_hrs": rna_y,
            "y_pred_hrs": rna_oof,
            "error_hrs":  np.abs(rna_y - rna_oof),
        })
        micro_oof_df = pd.DataFrame({
            "modality":   "Microbial",
            "y_true_hrs": micro_y,
            "y_pred_hrs": micro_oof,
            "error_hrs":  np.abs(micro_y - micro_oof),
        })
        oof_df = pd.concat([rna_oof_df, micro_oof_df], ignore_index=True)

        summary = {
            "model_type":    "FusionRidge_SeparateDatasets",
            "mode":          "separate_datasets",
            "rna_r2":        result["rna_r2"],
            "micro_r2":      result["micro_r2"],
            "rna_mae_hrs":   result["rna_mae_hrs"],
            "micro_mae_hrs": result["micro_mae_hrs"],
            "w_rna":         result["w_rna"],
            "w_micro":       result["w_micro"],
            "r2":            float(np.mean([result["rna_r2"], result["micro_r2"]])),
            "mae_hrs":       float(result["w_rna"] * result["rna_mae_hrs"]
                                   + result["w_micro"] * result["micro_mae_hrs"]),
        }

        # Save two separate graphs side by side
        fig, axes = plt.subplots(1, 2, figsize=(14, 6))

        for ax, y_t, y_p, label, color in [
            (axes[0], rna_y,   rna_oof,   "RNA (GTEx)",          "#2563eb"),
            (axes[1], micro_y, micro_oof, "Microbial (Qiita)",   "#7c3aed"),
        ]:
            ax.scatter(y_t, y_p, alpha=0.45, s=24, color=color, edgecolors="none")
            lo, hi = min(y_t.min(), y_p.min()), max(y_t.max(), y_p.max())
            ax.plot([lo, hi], [lo, hi], "k--", linewidth=1.5, label="Perfect")
            r2_  = r2_score(y_t, y_p)
            mae_ = mean_absolute_error(y_t, y_p)
            ax.text(0.05, 0.93, f"R² = {r2_:.4f}", transform=ax.transAxes,
                    fontsize=12, fontweight="bold")
            ax.text(0.05, 0.86, f"MAE = {mae_:.2f} hrs", transform=ax.transAxes,
                    fontsize=10)
            ax.set_title(f"{label}\nRidge-Calibrated OOF")
            ax.set_xlabel("Actual PMI (hours)")
            ax.set_ylabel("Predicted PMI (hours)")
            ax.legend(loc="lower right")
            ax.grid(True, linestyle="--", alpha=0.35)

        plt.suptitle("ForensicChrono — Fusion Meta-Model (Separate Datasets)",
                     fontsize=13, fontweight="bold", y=1.02)
        plt.tight_layout()
        os.makedirs("reports", exist_ok=True)
        png = "reports/fusion_model_predicted_vs_actual.png"
        svg = "reports/fusion_model_predicted_vs_actual.svg"
        fig.savefig(png, dpi=300, bbox_inches="tight")
        fig.savefig(svg, bbox_inches="tight")
        plt.close(fig)
        print(f"Regression graph saved -> {png}")

    # ── Save package ─────────────────────────────────────────────────────────
    with open(FUSION_MODEL_PATH, "wb") as f:
        pickle.dump(package, f)
    print(f"\nFusion model saved -> {FUSION_MODEL_PATH}")

    # ── Save results ─────────────────────────────────────────────────────────
    save_fusion_results(summary, oof_df)

    print("\n" + "=" * 70)
    print("FUSION META-MODEL COMPLETE")
    print("=" * 70)
    print(f"\nSummary:")
    for k, v in summary.items():
        print(f"  {k:<20}: {v}")


if __name__ == "__main__":
    main()